### PR TITLE
E_CLASSROOM-273 [Bugfix] Back button redirects to /categories if from…

### PR DESCRIPTION
**Pull request by catampongan**
### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-273

### Definition of Done
- [x] Back button redirects to /categories if from a subcategory

#### Main note
- Click any subcategory then click `Back Button`
#### Pages Affected
- http://localhost:3003/categories/1/sub

### Scenarios/ Test Cases
- [ ] Back button redirects to /categories if from a subcategory
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
sub

### CODE REVIEW

**Comment by ErickDoroy** [comment]
### Working 
- [x] Back button redirects to /categories if from a subcategory
------------
### Comments
- [x] Subcategory name and Back button must have margin

subcategoryerror

- [x] Subcategory name should not hand cursor and not redirects to /categories if from a subcategory

subcaterror

- [x] Back button in quizzes not working properly it will not redirect to the right page

error3

--------------
- Total Test Time: 0.25 hrs
- Total Comments: 3

**Comment by ErickDoroy** [comment]
### APPROVE #112

--------------

- Total Test Time: 0.25 hrs
- Total Comments: 3

**Comment by ErickDoroy** [comment]
## Approved PR #112

----------
- Total Test Time: 0.75 hr
- Total Iterations: 1
- Total Comments: 3

**Review by karlolee50 — APPROVED** [review]
Review time: 5 minutes
Comment/s: 0

**Pull request merged**
