### PR TITLE
Feature/e classroom 118 integration student password reset

### PR DESCRIPTION
**Pull request by CaneteJoash**
### Issue Link

https://framgiaph.backlog.com/view/E_CLASSROOM-118
### Definition of Done
- [x] Integrate password reset page with the backend.

### Commands to Run
N/A

#### Main note
-  Create User link : http://localhost:3003/registration
-  I created Backend repository link :  https://github.com/framgia/sph-classroom-els-be/pull/14
#### Pages Affected
- http://localhost:3003/reset-password

### Scenarios/ Test Cases
- [x] Integrate password reset page with the backend.
#### User Interface
- [x] N/A
#### User Experience 
- [x] Can reset password
#### Functionality
- [x] it should send token
- [x] can resetPassword
### Screenshots

image

image

image

### CODE REVIEW

**Comment by geneno99** [comment]
### Approved PR #22 
- Can reset password 
- Able to send email confirmation
- Able to change password successfully
- Display validation message





----
- Total Test time: 0.5 hr
- Total Iterations: 0
- Total Comments: 0

**Comment by erronerron** [comment]
- [ ] No error message if inputted incorrect email
Screenshot from 2021-11-10 18-03-37

- [ ] Fix styling when password confirmation has error validation
Screenshot from 2021-11-10 18-04-07

**Comment by erronerron** [comment]
- [ ] No error message displayed. Please confirm
Screenshot from 2021-11-10 18-24-38

**Comment by geneno99** [comment]
### Approved PR #22 
- Able to display prompt when valid email is resetting password
- Able to send email confirmation
- Able to change password successfully
- Display validation message

<details><summary>Screenshot</summary>








</details>

----
- Total Test time: 0.75 hr
- Total Iterations: 2
- Total Comments: 3

**Comment by erronerron** [comment]
- [ ] Do not sign in the user directly, redirect to login page after setting new password. There is also error in current implementation: User was unable to logout.

https://user-images.githubusercontent.com/88467532/141247145-9d11e5c8-5a2a-4d7c-a462-d7449c58c53b.mp4

**Pull request merged**
