### PR TITLE
E_CLASSROOM-260 [UI] Adding/Editing Nested Subcategories

### PR DESCRIPTION
**Pull request by Teraaay**
### Issue Link

https://framgiaph.backlog.com/view/E_CLASSROOM-260

### Definition of Done
-  [x] Able to display Modal to set Location when adding or editing a category.

### Commands to Run
N/A
#### Main note
- Displaying the subcategory for every parent category hasn't been implemented yet, this UI only temporarily shows the parent categories.
#### Pages Affected
- ADD CATEGORY [ADMIN]: http://localhost:3003/admin/add-category
- EDIT CATEGORY [ADMIN]: http://localhost:3003/admin/edit-category

### Scenarios/ Test Cases
- [ ] it should ` display a Modal to Change Location` when `clicking the Open Icon that is in the Location Input Field` 

### Screenshots
CHANGE LOCATION MODAL UI FOR ADD AND EDIT CATEGORY

### CODE REVIEW

**Comment by CaneteJoash** [comment]
### Working

### Add Category 
- [x] Able to display modal
- [x]  when hover, the move icon was displayed.

### Edit Category
- [x] Able to display modal
- [x]  when hover, the move icon was displayed.

### Comment/s
- [x] Please use the icon same in figma

###figma
image
### app

image

- [x] in location, when clicking the input field, the modal should display. Also please fix the icon because when we minimize the description (input field) the icon will push to the top.

- please refer my record.  


------
- Total Test Time: 1 hr

**Comment by CaneteJoash** [comment]
### Comment
- [x] Please fix the position and size of the icon, refer this in figma.

### screenshots 
### figma
image

### app
image

**Comment by CaneteJoash** [comment]
### Working

### Add Category 
- [x] Able to display modal
- [x]  when hover, the move icon was displayed.

### Edit Category
- [x] Able to display modal
- [x]  when hover, the move icon was displayed.

- [x] able to fix the icon when the description was minimized.

- [x] Able to fix the icon same in figma

image (1)

------
- Total Test Time: 1 hr
- Total comments: 2

**Review by karlolee50 — APPROVED** [review]
Review time: 15 minutes
Comment/s: 0

**Pull request merged**
