### PR TITLE
E_CLASSROOM-138 [Integration] [Student] Quiz List Pagination

### PR DESCRIPTION
**Pull request by Teraaay**
### Definition of Done
- [x] Create pagination functionality for list of quizzes

Note: Consider the following for pagination:
    - Current Page
    - PerPage Items
    - Total Items

### Commands to Run

N/A

#### Main note
- Please create more quizzes to test the Pagination Functionality.
- Please wait for a couple of seconds when changing a page, It takes time for the quizzes to load when changing a page.
#### Pages Affected
- http://localhost:3003/categories/1/quizzes

### Scenarios/ Test Cases
- [ ] It should display data (12 datas per page) depending on page number
#### User Interface
- [ ] when `action` should `expected behavior`
#### User Experience 
- [ ] when `action` should `expected behavior`
#### Functionality
- [ ] it should return value when `action`
### Screenshots
PAGE 1 OF QUIZZES
image

PAGE 2 OF QUIZZES
image

NO RESULTS FOUND
image

### CODE REVIEW

**Comment by geneno99** [comment]
### Working
- [x] Pagination is working properly
- [x] `Prev` and `Next` button is working properly
- [x] Able to keep pagination history even after reloading the page

### Comment

- [ ] Make the `curose:not-allowed` in Prev` and `Next` button when the pagination ins the first index and vice versa to the last index
- Reference: https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=not-allowed

- [ ] Can you improved the loading of when changing pages it seems take more than 5 seconds. Please confirm :bow
-----
- Test time: 0.5 hr

**Comment by erronerron** [comment]
- [ ] Make the category information dynamic.
- [ ] Make use of useHistory from react-router-dom to avoid reloading the whole page.
- [ ] For the 'pageCount', please refer to the 'last_page' data returned from the backend.

**Comment by geneno99** [comment]
### Working
- Able to fix all comments

### Comment
- [ ] `Prev` and `Next` button is displaying again after reloading the page even the pagination is in the first and last index. Please confirm 

Quiz List Pagination1

----
- Test time: 0.75 hr

**Comment by geneno99** [comment]
## Approved PR #27 
- [x] Pagination is working properly
- [x] `Prev` and `Next` button is working properly
- [x] Able to keep pagination history even after reloading the page

https://user-images.githubusercontent.com/58454573/142136470-c8918dea-9675-4ebc-8ad6-1409ba7273c8.mp4

-----
- Total Test time: 1 hr
- Total Iterations: 2
- Total Comments: 3

**Comment by erronerron** [comment]
- [ ] Pagination number is shown if no results found.
Screenshot from 2021-11-17 13-00-59

**Pull request merged**
