### PR TITLE
E_CLASSROOM-171 [Bugfix] [FE] [Student] Fix Ordering of Categories if…

### PR DESCRIPTION
**Pull request by ErickDoroy**
### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-171
### Definition of Done
- [ ] Order of categories has space in the middle if items are even

#### Pages Affected
- http://localhost:3003/categories
- http://localhost:3003/categories/1/sub
- http://localhost:3003/categories/1/quizzes

### Scenarios/ Test Cases
- [ ] it should order of categories has space in the middle if items are even
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
updatecategory
updatequiz
updatesubcat

### CODE REVIEW

**Comment by Johnpaullim** [comment]
### Working 

- [ ] Able to fix the bug.
- [ ] Order of categories has space in the middle if items are even
<details><summary>Screenshot</summary>

eriks

</details>

----
- Total Test time: 0.5 hr

**Comment by erronerron** [comment]
- [ ] Fix Quiz List page
screencapture-localhost-3003-categories-1-quizzes-2021-11-24-17_18_56

**Comment by Johnpaullim** [comment]
### Working 

- [ ] Able to fix the bug.
- [ ] Able to fix the spacing of categories
- [ ] fix the bug in quizzes page


quiz

quizDB

**Comment by erronerron** [comment]
- [ ] Fix browser console errors on Quiz list page:
Screenshot from 2021-11-26 12-03-53

**Comment by erronerron** [comment]
- [ ] Fix the spacing when no results are found
screencapture-localhost-3003-categories-10-quizzes-2021-11-26-13_13_41

**Pull request merged**
