### PR TITLE
Feature/e classroom 50 markup student quizzes 2/3

### PR DESCRIPTION
**Pull request by catampongan**
### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-50
### Definition of Done
- [x] Create markup page when taking a quiz (including different question types).

### Commands to Run
N/A

#### Main note
- N/A
#### Pages Affected
- `/categories/{id}/quizzes/{id}/questions`

### Scenarios/ Test Cases
- [x] Create markup page when taking a quiz (including different question types).
#### User Interface
- N/A
#### User Experience 
- N/A
#### Functionality
- N/A
### Screenshots
Screenshot 2021-11-04 180351
Screenshot 2021-11-04 180404
Screenshot 2021-11-04 180426

### CODE REVIEW

**Comment by geneno99** [comment]
## Comment

- [ ] Change font-weight to `400px`

screenbud-3cd0e4a5-5104-49b7-8f7e-7a6c3f15582a

-----
- Test time: 0.25 hr

**Comment by geneno99** [comment]
## Approved PR #11 

- [x] Able to create markup for quiz item
- [x] Able implement same as styling, position, and alignment as FIGMA

<details><summary>Screenshot</summary>

Screenshot 2021-11-03 190128
</details>

## Note
- For the implementation for now it is in single page since number of quiz item is not yet decided

-----
- Total Test time: 0.5 hr
- Total Iterations: 1
- Total Comments: 1

**Comment by erronerron** [comment]
Each question should on separate pages. And also, please fix conflicts

**Comment by geneno99** [comment]
### Working
- Able to make quiz item in different pages

## Comments
1. Make the font-weight to 400px
2. Please add space check FIGMA in the last page
Screen Shot 2021-11-05 at 12 29 30 PM

Screen Shot 2021-11-05 at 12 30 54 PM


-----
- Test time: 0.75 hr

**Comment by geneno99** [comment]
### Approved PR #11 

- [x] Able to create markup for quiz item
- [x] Quiz items are implemented in different page
- [x] All buttons is working properly
- [x] Able implement same as styling, position, and alignment as FIGMA

<details><summary>Screenshot</summary>

Screen Shot 2021-11-05 at 1 24 11 PM

Screen Shot 2021-11-05 at 1 26 13 PM

Screen Shot 2021-11-05 at 1 26 52 PM
</details>


### Note
- Timer is not implement in this PR

-----
- Total Test time: 0.75 hr
- Total Iterations: 2
- Total Comments: 3

**Pull request merged**
